name: Release
on: workflow_dispatch
permissions:
  # mvn release:prepare pushes commits and a tag
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-release-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-release-
            maven-build-${{ hashFiles('**/pom.xml') }}
            maven-build-
            maven-

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"

      - name: Maven Release
        run: ./mvnw -B release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}
